### ISSUE TITLE
Setting the favicon

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby-starter-default#18]
Where is `this.props.favicon` supposed to come from here?

https://github.com/gatsbyjs/gatsby-starter-default/blob/master/html.js#L34

**Comment by KyleAMathews** [comment]
Oh oops. That was old code that I never noticed and deleted. Just removed it.

**Comment by mbliok** [comment]
Hi Kyle,
How can I add a favicon in gatsby-starter-default?

` tried in default-html.js, but after runing site the code is gone, it is deleted!!!!


import favicon from '../src/assets/images/favicon-16x16.png';

`return (
      <html {...this.props.htmlAttributes}>
        <head>
         
          {css}

          <link rel="shortcut icon" href={favicon} />`
