### ISSUE TITLE
Add nav bar?

### ISSUE THREAD

**Issue by sebastianbarfort** [gatsbyjs/gatsby-starter-default#2]
Hi,

thanks for a great default starter template. I want to add a navigation bar, but can't figure out how to do that. Is there some documentation I can read or can someone help me with this?

Best,
Sebastian

**Comment by KyleAMathews** [comment]
Have you built sites with React.js before? If you understand React, it's not hard otherwise...

Gatsby is still new. The hope is that down the road there'll be more developed starters that have stuff like nav bars built-in.

**Comment by KyleAMathews** [comment]
@sebastianbarfort this starter now comes with a simple nav bar which you can see at http://gatsbyjs.github.io/gatsby-starter-default/
