### ISSUE TITLE
linkPrefix in markdown doesn't work

### ISSUE THREAD

**Issue by dbismut** [gatsbyjs/gatsby-starter-default#26]
Hello - it looks like relative links in the markdown are not prefixed using the loader in the starter-default.

My workaround was to modify the `markdown-loader` and use the `markdown-it` plugin `markdown-it-replace-link`:

```javascript

var isProduction = process.env.NODE_ENV === 'production';

var md = markdownIt({
  html: true,
  linkify: true,
  typographer: true,
  replaceLink: function (link, env) {
    return isProduction ? '/prefix-link' + link : link
  }
})
  .use(require('markdown-it-replace-link'))
```

And to alter the script in the `package.json` file to set the `NODE_ENV`.

```json
"scripts": {
  ...
  "deploy": "NODE_ENV=production gatsby build --prefix-links
}
```

Then `yarn deploy` or `npm deploy` makes it for me, but I was wondering if there was a prettier way to do this by accessing the `config.toml` from the loader and without explicitly setting the node environment variable.

**Comment by KyleAMathews** [comment]
Oh excellent work! Yes, links are only prefixed in JS environment which doesn't happen automatically (atm) for links in Markdown files.

You shouldn't need to set the `NODE_ENV` var as Gatsby sets that to production itself when running `gatsby build` as there's too many things that need that set to leave it to users.

So this could be a good thing to add to the core markdown-loader. I've heard at least one other person complain about this and it does break expectations for how things should work.

Would you be interested in creating a PR to add this? One thing that'd need updated is add a check to see if the link is relative before prefixing it (if the `replaceLink` plugin doesn't already do this).

**Comment by dbismut** [comment]
I'd be happy to PR, but two questions first (I'm not exactly a pro developer):

1. `NODE_ENV` doesn't seem to be accessible from the loader `index.js` file, `console.log(process.env.NODE_ENV)` returns `undefined`).

2. Actually we should prefix when `--prefix-links` has been set, independently of running in production mode or not. How do I access this from the loader `index.js` file? I understand there is a `__PREFIX_LINKS__` variable set in webpack, but I'm not sure how to access it.

**Comment by dbismut** [comment]
Oh and I checked... `replaceLink` doesn't check anything, it parses all links, even absolute URLs... So as you hinted, we'd need to check if the URL is an absolute path before prefixing it. One other solution would be to add `?prefix=true` in the URL, but I'm not sure this is a good idea.

**Comment by KyleAMathews** [comment]
Oh... interesting. That should be fixed then. We could use
https://www.npmjs.com/package/is-relative for this.

**Comment by dbismut** [comment]
Great! What about my comment above?

**Comment by KyleAMathews** [comment]
Which one?

**Comment by dbismut** [comment]
How to access --prefix-links from the index.js file in the loader?

**Comment by KyleAMathews** [comment]
Checkout https://github.com/gatsbyjs/gatsby/blob/66d7bf51e20f5ebcdfeb95c10e857282cd78512f/lib/isomorphic/gatsby-helpers.js

There's the `__PREFIX_LINKS__` global which says if `--prefix-links` was used when running gatsby build and then the config module has the actual link prefix.

**Comment by dbismut** [comment]
I understand but I can't access that global from the index.js file from the loader... `console.log(__PREFIX_LINKS__)` returns `undefined` in the terminal... Sorry if this is a dumb one.

**Comment by KyleAMathews** [comment]
Oh right... not being too sharp here. Hmmm yeah. We only add the environment variable to the webpack context now not the node.js so it isn't available in node.js code.

**Comment by KyleAMathews** [comment]
Could you add a PR to add the global here as well? https://github.com/gatsbyjs/gatsby/blob/3792215f24b3b87d3fa5ecb5f37e57bad9ebf4c2/lib/bin/cli.js#L45

I think that'd be the right pattern.

**Comment by dbismut** [comment]
Hey @KyleAMathews, thanks for your help! I'm trying to mend pieces together, but I'm not sure how to `require` the `config.toml` in the `index.js` from the loader to get the `linkPrefix`?

**Comment by KyleAMathews** [comment]
You'd have to read it off the filesystem and parse it. Webpack has a loader
setup for it already.

**Comment by dbismut** [comment]
Hey - checking something before doing the PR to be sure we're on the same page.
This is what I have:

```javascript
// [...]

var config

try {
   config = toml.parse(fs.readFileSync(path.resolve(__dirname, '../../config.toml')))
 } catch (error) {
   console.log("Couldn't load your site config")
 }

var linkPrefix = config && config.linkPrefix || '/'

var md = markdownIt({
  html: true,
  linkify: true,
  typographer: true,
  replaceLink: function (link) {
    if (process.env.PREFIX_LINK && path.isAbsolute(link)) {
      return linkPrefix + link
    }
    return link
  }
})
  // [...]
  .use(require('markdown-it-replace-link'))
```

This produces the following results:

```
linkPrefix = ""

Link to "/" -> /
Link to "/dir" -> /dir
Link to "../dir" -> ../dir
Link to "http://www.google.com" -> http://www.google.com

---

linkPrefix = "/your-project"

Link to "/" -> /your-project/
Link to "/dir" -> /your-project/dir
Link to "../dir" ->../dir
Link to "http://www.google.com" -> http://www.google.com
```

Is that what you had in mind?

**Comment by KyleAMathews** [comment]
Yeah that looks great! Please just add a test in your PR so we can keep
things working great!

**Comment by dbismut** [comment]
Err sorry but what tests? This repo doesn't have any tests? Should I fix the default markdown loader from `gatsby`?

**Comment by KyleAMathews** [comment]
Oh sorry yeah, that's what I meant. And add a PR here (though the tests
aren't necessary here)

**Comment by dbismut** [comment]
This should be fixed by PR https://github.com/gatsbyjs/gatsby/pull/710 on gatsby. Once the PR is approved there, I'll make a PR here on the `gatsby-starter-default`. By the way @KyleAMathews, any reason why custom loaders can't be written in ES6?
