### ISSUE TITLE
`rhythm` is not exported from `utils/typography`

### ISSUE THREAD

**Issue by kongakong** [gatsbyjs/gatsby-starter-default#27]
In `/pages/_template.jsx `, this line

     import { rhythm } from "../utils/typography"

cause this exception:

    TypeError: (0 , _typography.rhythm) is not a function

I think the function by  the name `rhythm` is not implemented

**Comment by KyleAMathews** [comment]
I wasn't able to reproduce this from a fresh install (`gatsby new test; cd test; gatsby develop`).

Any more information you can add about your setup? Any changes you've made?

`rhythm` is a function on the typography object that's exported from `utils/typography.js`.

**Comment by kongakong** [comment]
Seems like related to my local environment (osx) and the use of nvm
