### ISSUE TITLE
Issues with default template

### ISSUE THREAD

**Issue by saviomuc** [gatsbyjs/gatsby-starter-default#29]
Hi,

first of all, thanks for your work. I like it a lot.
However I have some questions and suggestions regarding the starter default to make it even better.

### Travis CI config
The travis config is very specific and doesn't contribute any value to the starter template. If somebody needs to set up a CI specific config it's likely they can and will add their own.

### package.json
- gh-pages
The package file has a dependency on gh-pages which is not necessary to understand the example template. In my opinion it would be much better to add a section in the documentation to explain how one can deploy to gh-pages than to add something which is not part of the "core" example.

- prettier
The dependency is missing and it refers to wrong and missing paths.

 - React dependencies are not declared
I guess they are installed as peer dependencies of Gatsby. This would force me to disable `import/no-extraneous-dependencies` so my lint does not fail. Imo that's not a good solution. Is there a reason for that?

### gitignore
It looks like the .gitignore is based on you personal config. I suggest to remove everything which is not related to the example to keep it as clean as possible.

### Missing Eslint config
All code should follow some guidelines. It would be great if a basic eslint config could be added (maybe pull in https://github.com/yannickcr/eslint-plugin-react).

### typography.css
The name is misleading. The file actually contains reset and typography related styles. This could actually be moved into a base component with a base css.

### Code style
- The examples use mainly React.Components where in most cases stateless functional components would be the preferred choice. For instance html.js could be rewritten this way
```
const getCSS = () => {
  if (process.env.NODE_ENV === 'production') {
    return (
      <style
        dangerouslySetInnerHTML={{
          __html: require('!raw!../public/styles.css'),
        }}
      />
    );
  }
  return undefined;
};

const HTML = ({
  body,
  headComponents,
  postBodyComponents,
}) => (
  <html lang="en">
    <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      />
      {headComponents}
      {getCSS()}
    </head>
    <body>
      <div
        id="___gatsby"
        dangerouslySetInnerHTML={{ __html: body }}
      />
      {postBodyComponents}
    </body>
  </html>
);
```
- Mix of tagged template literals and  single / double quotes. There is no reason for tagged template literals so I'd remove them. Also it would be nice to unify the quotes. For instance in the `index.js`
- Class properties are used throughout the project to set propTypes. However they still are experimental and therefore I suggest to use the default way to declare PropTypes instead.

 I understand that this is a lot of nitpicking. However I would love to see a lot of people adopting high quality and consistent code. 

Btw. if you agree we could create a list and I will make dedicated PRs for all the issues.

**Comment by KyleAMathews** [comment]
These are fantastic suggestions. 100% agree the default starter should be
as perfect as possible. Could you out together a PR with these changes?

On eslint, I'd really like to copy what create-react-app does here.

**Comment by saviomuc** [comment]
Thanks for your feedback @KyleAMathews!

I will work on it, but first I need some clarification on this one:

"React dependencies are not declared" < Should we set no-extraneous-dependencies to false? The default create-react-app eslint will complain about that. A better approach (in the future) might be to explicitly declare react dependencies in the package.json.

**Comment by KyleAMathews** [comment]
I'd rather not declare react as a dependency by default. You certainly can if you know what you're doing but part of the point of Gatsby is you can use it without really knowing what you're doing.

**Comment by saviomuc** [comment]
@KyleAMathews I created a PR. However there seems to be an issue with the build. Let's continue in the PR.
