### ISSUE TITLE
Not able to create other pages

### ISSUE THREAD

**Issue by cgarvis** [gatsbyjs/gatsby-starter-default#3]
`gatsby build` generates the correct layout, but React-Router is throwing 

```Warning: No route matches path "/company". Make sure you have <Route path="/company"> somewhere in your routes```'

I've tried the following:

* `/pages/company.js`
* `/pages/company.jsx`
* `/pages/company/index.js`
* `/pages/company/index.jsx`

**Comment by cgarvis** [comment]
So I found that if you go to `/company/` then it works.  Anyway we can get this to not need the trailing slash?

**Comment by KyleAMathews** [comment]
Eventually yes. See [this issue comment](https://github.com/gatsbyjs/gatsby/issues/30#issuecomment-138387901). As that comment suggests, removing the trailing slash has to be supported by whatever you'll be using to host your site e.g. Nginx. The idea is that you could enable "slash-less" mode in your site config so trailing slashes wouldn't be added to routes. If interested, I'd love a PR for that.

**Comment by obvio171** [comment]
I couldn't find a documentation example on how to create jsx pages instead of md. @cgarvis, could you please post a skeleton of yours? Thanks!

**Comment by KyleAMathews** [comment]
@obvio171 `.jsx` files should just work. What problems are you hitting?

**Comment by cgarvis** [comment]
We use `.js` as the extension.  I ended up make sure all the links were not "slash-less"

**Comment by obvio171** [comment]
@KyleAMathews they do, I just wasn't sure what to put in them :) Found out though, thanks!

**Comment by TimonVS** [comment]
This is kind of a major issue in my opinion. I just spent 30 minutes trying to figure out why my new pages were showing 404's.

**Comment by KyleAMathews** [comment]
@TimonVS you were expecting slashless urls as well?

Something that could help is if Gatsby had a "sitemap" page that was auto-generated during dev mode.

**Comment by SachaG** [comment]
Just ran into that myself. How about at least adding a mention about slashless routes not working to the docs?

**Comment by KyleAMathews** [comment]
@SachaG that would be a great start — could you add it? Perhaps to the FAQ?

**Comment by KyleAMathews** [comment]
And expanding on my "sitemap" idea above. I think in dev, the 404 page should just be the sitemap — something like "hey, we couldn't find that page... here are the pages we do know about". Also would be easy to add a little search box for larger sites.
