### ISSUE TITLE
Doing a `gatsby new` doesn't work out of the box with `gatsby develop`

### ISSUE THREAD

**Issue by mboudreau** [gatsbyjs/gatsby-starter-default#32]
Giving this error:
```
error A local install of Gatsby exists but failed to load.


  Error: Cannot find module 'webpack/lib/removeAndDo'
  
  - module.js:20 require
    internal/module.js:20:19
  
  - ExtractedModule.js:30 Object.<anonymous>
    [pact.io]/[extract-text-webpack-plugin]/ExtractedModule.js:30:42
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.js:7 Object.<anonymous>
    [pact.io]/[extract-text-webpack-plugin]/index.js:7:23
```

Looking closer at my node_modules, it seems like webpack was never downloaded.  Webpack-core and a few others were, just not the main package, which is weird.  Tried blowing away node_modules, clearing cache and retrying, no dice. Not too sure what's going on.

**Comment by KyleAMathews** [comment]
Make sure to delete any lock files that were created as well.

**Comment by ponddesign** [comment]
@mboudreau I ran into a similar issue due to installing my `gatsby new` project within another project which already had a package.json and its own dependencies. Moving out of that project and into a clean directory resolved my issue.

**Comment by jonathanprozzi** [comment]
I was encountering a similar issue and I followed these directions: https://babeljs.io/env
added a .babelrc and changing the presets to "env" worked for me.
