### ISSUE TITLE
Hot reloading breaks links

### ISSUE THREAD

**Issue by ralrom** [gatsbyjs/gatsby-starter-default#33]
[package-lock.txt](https://github.com/gatsbyjs/gatsby-starter-default/files/1301701/package-lock.txt)

# Problem:

When using `gatsby develop`, changes to page components are reflected immediately; however ,a javascript error caused by hot reloading breaks the router.

The console throws this error: `Warning: You cannot change <Router history> browser.js:49` after which links stop working.

# Steps to reproduce

- `npm install --global gatsby-cli`
- `gatsby new gatsby-site`
- `cd gatsby-site`
- `gatsby develop`
- Add text on `src/pages/index.js` and save. The text will appear, but the hot reloading causes a javascript error, after which links stop working

**System info**

Node.js: v8.4.0
npm: 5.3.0
package.json:
```
"dependencies": {
    "gatsby": "^1.9.17",
    "gatsby-link": "^1.6.15",
    "gatsby-plugin-react-helmet": "^1.0.5"
  },
```

**Comment by KyleAMathews** [comment]
Sorry about the breakage — https://github.com/gatsbyjs/gatsby/pull/2110 has the fix. Upgrade to the latest Gatsby and hot reloading will work again.

**Comment by KyleAMathews** [comment]
And thanks for the nice reproduction steps! Used them when working on the fix.
