### ISSUE TITLE
gatsby new XXX   Error

### ISSUE THREAD

**Issue by shinley** [gatsbyjs/gatsby-starter-default#36]
shinley:~ shinley$ gatsby new gatsby-site
info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
remote: Counting objects: 614, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 614 (delta 2), reused 6 (delta 2), pack-reused 607
Receiving objects: 100% (614/614), 562.17 KiB | 70.00 KiB/s, done.
Resolving deltas: 100% (346/346), done.
success Created starter directory layout
info Installing packages...
npm WARN gatsby-starter-default@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webpack-hot-middleware@2.20.0 (node_modules/webpack-hot-middleware):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/shinley/gatsby-site/node_modules/.staging/webpack-hot-middleware-6cd7911c'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: value-equal@0.4.0 (node_modules/value-equal):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/shinley/gatsby-site/node_modules/.staging/value-equal-5e1d8e10'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nanomatch@1.2.5 (node_modules/nanomatch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/shinley/gatsby-site/node_modules/.staging/nanomatch-681f0324'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: history@4.7.2 (node_modules/history):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/shinley/gatsby-site/node_modules/.staging/history-6b72df96'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: base@0.11.2 (node_modules/base):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/shinley/gatsby-site/node_modules/.staging/base-79c3750f'

npm ERR! code ETARGET
npm ERR! notarget No matching version found for bash-glob@1.0.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby-starter-default'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shinley/.npm/_logs/2017-11-07T08_13_26_311Z-debug.log
error Command failed: npm install

  Error: Command failed: npm install

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14

**Comment by KyleAMathews** [comment]
Looks like a random error. Try again?

**Comment by shinley** [comment]
I tried many times yesterday. Today it's ok. Thank you !
