### ISSUE TITLE
gatsby new with node >= 8 currently fails to build

### ISSUE THREAD

**Issue by semateos** [gatsbyjs/gatsby-starter-default#41]
Looks like conflict between version of node and the version of webpack, results in:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                     14:02:38

This relative module was not found:

* ./index.css in ./src/layouts/index.js
```

Works fine in node 6... so that's good! Also, I didn't see a recommended version of node anywhere on gatsby getting started (I think it just says anything >=4)...

**Comment by KyleAMathews** [comment]
I'm using Node 8 w/o troubles. Node 6 + 8 are supported. The error is just saying you're missing a file.

**Comment by semateos** [comment]
The file is there. Have you done a fresh gatsby new? I was just following the getting started steps today and it failed out of the box with 8 and 9 but worked with 6 - exact same file structure because I deleted everything and did a fresh ‘new’ resulting in a clean clone each time.

**Comment by KyleAMathews** [comment]
Yeah, it was a fresh gatsby new.

It could maybe be this PR that was released earlier https://github.com/gatsbyjs/gatsby/pull/3283

Could one of you try installing style-loader@0.13.0 `npm install style-loader@0.13.0` and see if it starts working?

**Comment by joeptacek** [comment]
i got the above error when doing `gatsby new proj` and then `cd proj && gatsby develop`. no error when i tried again after installing the earlier version of style-loader.

**Comment by KyleAMathews** [comment]
Seeing other people report the same thing https://twitter.com/Lehanism/status/951397594953076737

I'm reverting the above PR :-(

**Comment by KyleAMathews** [comment]
Published 1.9.153 — would appreciate someone testing upgrading to see if things work now

**Comment by semateos** [comment]
Just tried fresh install of gatsby@1.9.153 with node@9.3.0 - same error as above. Tried `npm install style-loader@0.13.0` and that fixes it.

**Comment by nicolairobles** [comment]
I'm using Node 6 and getting the below error. I don't even get a new directory:
```
gatsby new gatsby-site
info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

error Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-default.git gatsby-site --single-branch


  Error: Command failed: git clone git://github.com/gatsbyjs/gatsby-starter-defa  ult.git gatsby-site --single-branch
```

**Comment by KyleAMathews** [comment]
GitHub wasn't responding temporarily. If you try gatsby new again it should work.

**Comment by cutemachine** [comment]
I set 1.9.153 in package.json and did a `npm install` after removing the whole node_modules. This resolved the issue for me.

**Comment by trailofdad** [comment]
@KyleAMathews using this version works for me as well. Thanks!

**Comment by KyleAMathews** [comment]
Great!

**Comment by KyleAMathews** [comment]
Thanks @trailofdad and @cutemachine for testing!

**Comment by joeptacek** [comment]
so at this point, gatsby@1.9.153 is back to using style-loader@0.13.0 but gatsby-starter-default still has gatsby@1.9.149 in its package.json. thus for the time being folks doing `gatsby new proj` will need to edit package.json or do `npm update gatsby` from the project directory to avoid bugs, right?

**Comment by KyleAMathews** [comment]
Ugh, forgot to push the upgrade I did locally. It's updated now.

**Comment by mariohernandez** [comment]
It looks like running `npm install style-loader@0.13.0` solved the issue for me.  I am using node 9+
