### ISSUE TITLE
[v2] Deprecation warning occurs with global graphql

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby-starter-default#61]
The v2 branch has a global graphql object declared that will be deprecated in v3.
```
warning Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
/Users/snatera/projects/gatsby-landing-sites/src/components/layout.js
```

The fix is simple. Follow the warning message.

**Comment by naheller** [comment]
What about when I'm asked to make the import in a `.cache` file that gets overwritten by Gatsby?

```
Import it instead like:  import { graphql } from 'gatsby' in file:
/Users/nate/Projects/my-blog/.cache/fragments/image-sharp-fragments.js
```

**Comment by KyleAMathews** [comment]
@naheller looks like that was fixed by @m-allanson here: https://github.com/gatsbyjs/gatsby/pull/6160
