### ISSUE TITLE
Change repository preview site link's protocol to https

### ISSUE THREAD

**Issue by jumpalottahigh** [gatsbyjs/gatsby-starter-default#70]
GitHub pages provide https, so no reason not to link to the preview page using it.

![image](https://user-images.githubusercontent.com/4155121/43033083-4ce663c6-8ccc-11e8-9962-21ecb82258c7.png)

**Comment by m-allanson** [comment]
Good idea @jumpalottahigh, I've just updated the repo. Thanks!
