### ISSUE TITLE
`gatsby develop` gives me this error 

### ISSUE THREAD

**Issue by ajitStephen** [gatsbyjs/gatsby-starter-default#82]
`error There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"?`

using 
mac OS 10.13.6
node v8.11.3
npm 5.6.0
yarn 1.9.2
gatsby 1.1.58

can you please explain ?

**Comment by KyleAMathews** [comment]
The `gatsby` package isn't installed. Check that it's in your package.json and if it is, try removing `node_modules` and reinstalling.

**Comment by ajitStephen** [comment]
Already had gatsby installed globally. As tuts instructed. 
https://www.gatsbyjs.org/tutorial/part-one/#install-the-hello-world-starter 

I followed the tuts with beta version, its works for me. That's fine for now :)
